In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot  as plt

In [2]:
df = pd.read_csv("D:\onedrive\Desktop\CIC DDOS 2017 DATA_SET\Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv")

In [3]:
df.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,389,113095465,48,24,9668,10012,403,0,201.416667,203.548293,...,32,203985.500,5.758373e+05,1629110,379,13800000.0,4.277541e+06,16500000,6737603,BENIGN
1,389,113473706,68,40,11364,12718,403,0,167.117647,171.919413,...,32,178326.875,5.034269e+05,1424245,325,13800000.0,4.229413e+06,16500000,6945512,BENIGN
2,0,119945515,150,0,0,0,0,0,0.000000,0.000000,...,0,6909777.333,1.170000e+07,20400000,6,24400000.0,2.430000e+07,60100000,5702188,BENIGN
3,443,60261928,9,7,2330,4221,1093,0,258.888889,409.702161,...,20,0.000,0.000000e+00,0,0,0.0,0.000000e+00,0,0,BENIGN
4,53,269,2,2,102,322,51,51,51.000000,0.000000,...,32,0.000,0.000000e+00,0,0,0.0,0.000000e+00,0,0,BENIGN

In [4]:
#df['Destination Port']
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170366 entries, 0 to 170365
Data columns (total 79 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0    Destination Port             170366 non-null  int64
 1    Flow Duration                170366 non-null  int64
 2    Total Fwd Packets            170366 non-null  int64
 3    Total Backward Packets       170366 non-null  int64
 4   Total Length of Fwd Packets   170366 non-null  int64
 5    Total Length of Bwd Packets  170366 non-null  int64
 6    Fwd Packet Length Max        170366 non-null  int64
 7    Fwd Packet Length Min        170366 non-null  int64
 8    Fwd Packet Length Mean       170366 non-null  float64
 9    Fwd Packet Length Std        170366 non-null  float64
 10  Bwd Packet Length Max         170366 non-null  int64
 11   Bwd Packet Length Min        170366 non-null  int64
 12   Bwd Packet Length Mean       170366 non-null  float64
 13   Bwd Packet Length Std        170366 non-null  float64
 14  Flow Bytes/s                  170346 non-null  float64
 15   Flow Packets/s               170366 non-null  float64
 16   Flow IAT Mean                170366 non-null  float64
 17   Flow IAT Std                 170366 non-null  float64
 18   Flow IAT Max                 170366 non-null  int64
 19   Flow IAT Min                 170366 non-null  int64
 20  Fwd IAT Total                 170366 non-null  int64
 21   Fwd IAT Mean                 170366 non-null  float64
 22   Fwd IAT Std                  170366 non-null  float64
 23   Fwd IAT Max                  170366 non-null  int64
 24   Fwd IAT Min                  170366 non-null  int64
 25  Bwd IAT Total                 170366 non-null  int64
 26   Bwd IAT Mean                 170366 non-null  float64
 27   Bwd IAT Std                  170366 non-null  float64
 28   Bwd IAT Max                  170366 non-null  int64
 29   Bwd IAT Min                  170366 non-null  int64
 30  Fwd PSH Flags                 170366 non-null  int64
 31   Bwd PSH Flags                170366 non-null  int64
 32   Fwd URG Flags                170366 non-null  int64
 33   Bwd URG Flags                170366 non-null  int64
 34   Fwd Header Length            170366 non-null  int64
 35   Bwd Header Length            170366 non-null  int64
 36  Fwd Packets/s                 170366 non-null  float64
 37   Bwd Packets/s                170366 non-null  float64
 38   Min Packet Length            170366 non-null  int64
 39   Max Packet Length            170366 non-null  int64
 40   Packet Length Mean           170366 non-null  float64
 41   Packet Length Std            170366 non-null  float64
 42   Packet Length Variance       170366 non-null  float64
 43  FIN Flag Count                170366 non-null  int64
 44   SYN Flag Count               170366 non-null  int64
 45   RST Flag Count               170366 non-null  int64
 46   PSH Flag Count               170366 non-null  int64
 47   ACK Flag Count               170366 non-null  int64
 48   URG Flag Count               170366 non-null  int64
 49   CWE Flag Count               170366 non-null  int64
 50   ECE Flag Count               170366 non-null  int64
 51   Down/Up Ratio                170366 non-null  int64
 52   Average Packet Size          170366 non-null  float64
 53   Avg Fwd Segment Size         170366 non-null  float64
 54   Avg Bwd Segment Size         170366 non-null  float64
 55   Fwd Header Length.1          170366 non-null  int64
 56  Fwd Avg Bytes/Bulk            170366 non-null  int64
 57   Fwd Avg Packets/Bulk         170366 non-null  int64
 58   Fwd Avg Bulk Rate            170366 non-null  int64
 59   Bwd Avg Bytes/Bulk           170366 non-null  int64
 60   Bwd Avg Packets/Bulk         170366 non-null  int64
 61  Bwd Avg Bulk Rate             170366 non-null  int64
 62  Subflow Fwd Packets           170366 non-null  int64
 63   Subflow Fwd Bytes            170366 non-null  int64
 64   Subflow Bwd Packets          170366 non-null  int64
 65   Subflow Bwd Bytes            170366 non-null  int64
 66  Init_Win_bytes_forward        170366 non-null  int64
 67   Init_Win_bytes_backward      170366 non-null  int64
 68   act_data_pkt_fwd             170366 non-null  int64
 69   min_seg_size_forward         170366 non-null  int64
 70  Active Mean                   170366 non-null  float64
 71   Active Std                   170366 non-null  float64
 72   Active Max                   170366 non-null  int64
 73   Active Min                   170366 non-null  int64
 74  Idle Mean                     170366 non-null  float64
 75   Idle Std                     170366 non-null  float64
 76   Idle Max                     170366 non-null  int64
 77   Idle Min                     170366 non-null  int64
 78   Label                        170366 non-null  object
dtypes: float64(24), int64(54), object(1)
memory usage: 102.7+ MB

In [5]:
X = df
X = X.drop(' Label',axis= 1)

In [6]:
y = df.iloc[:,78]

In [7]:
y

0         BENIGN
1         BENIGN
2         BENIGN
3         BENIGN
4         BENIGN
           ...
170361    BENIGN
170362    BENIGN
170363    BENIGN
170364    BENIGN
170365    BENIGN
Name:  Label, Length: 170366, dtype: object

In [8]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170366 entries, 0 to 170365
Data columns (total 78 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0    Destination Port             170366 non-null  int64
 1    Flow Duration                170366 non-null  int64
 2    Total Fwd Packets            170366 non-null  int64
 3    Total Backward Packets       170366 non-null  int64
 4   Total Length of Fwd Packets   170366 non-null  int64
 5    Total Length of Bwd Packets  170366 non-null  int64
 6    Fwd Packet Length Max        170366 non-null  int64
 7    Fwd Packet Length Min        170366 non-null  int64
 8    Fwd Packet Length Mean       170366 non-null  float64
 9    Fwd Packet Length Std        170366 non-null  float64
 10  Bwd Packet Length Max         170366 non-null  int64
 11   Bwd Packet Length Min        170366 non-null  int64
 12   Bwd Packet Length Mean       170366 non-null  float64
 13   Bwd Packet Length Std        170366 non-null  float64
 14  Flow Bytes/s                  170346 non-null  float64
 15   Flow Packets/s               170366 non-null  float64
 16   Flow IAT Mean                170366 non-null  float64
 17   Flow IAT Std                 170366 non-null  float64
 18   Flow IAT Max                 170366 non-null  int64
 19   Flow IAT Min                 170366 non-null  int64
 20  Fwd IAT Total                 170366 non-null  int64
 21   Fwd IAT Mean                 170366 non-null  float64
 22   Fwd IAT Std                  170366 non-null  float64
 23   Fwd IAT Max                  170366 non-null  int64
 24   Fwd IAT Min                  170366 non-null  int64
 25  Bwd IAT Total                 170366 non-null  int64
 26   Bwd IAT Mean                 170366 non-null  float64
 27   Bwd IAT Std                  170366 non-null  float64
 28   Bwd IAT Max                  170366 non-null  int64
 29   Bwd IAT Min                  170366 non-null  int64
 30  Fwd PSH Flags                 170366 non-null  int64
 31   Bwd PSH Flags                170366 non-null  int64
 32   Fwd URG Flags                170366 non-null  int64
 33   Bwd URG Flags                170366 non-null  int64
 34   Fwd Header Length            170366 non-null  int64
 35   Bwd Header Length            170366 non-null  int64
 36  Fwd Packets/s                 170366 non-null  float64
 37   Bwd Packets/s                170366 non-null  float64
 38   Min Packet Length            170366 non-null  int64
 39   Max Packet Length            170366 non-null  int64
 40   Packet Length Mean           170366 non-null  float64
 41   Packet Length Std            170366 non-null  float64
 42   Packet Length Variance       170366 non-null  float64
 43  FIN Flag Count                170366 non-null  int64
 44   SYN Flag Count               170366 non-null  int64
 45   RST Flag Count               170366 non-null  int64
 46   PSH Flag Count               170366 non-null  int64
 47   ACK Flag Count               170366 non-null  int64
 48   URG Flag Count               170366 non-null  int64
 49   CWE Flag Count               170366 non-null  int64
 50   ECE Flag Count               170366 non-null  int64
 51   Down/Up Ratio                170366 non-null  int64
 52   Average Packet Size          170366 non-null  float64
 53   Avg Fwd Segment Size         170366 non-null  float64
 54   Avg Bwd Segment Size         170366 non-null  float64
 55   Fwd Header Length.1          170366 non-null  int64
 56  Fwd Avg Bytes/Bulk            170366 non-null  int64
 57   Fwd Avg Packets/Bulk         170366 non-null  int64
 58   Fwd Avg Bulk Rate            170366 non-null  int64
 59   Bwd Avg Bytes/Bulk           170366 non-null  int64
 60   Bwd Avg Packets/Bulk         170366 non-null  int64
 61  Bwd Avg Bulk Rate             170366 non-null  int64
 62  Subflow Fwd Packets           170366 non-null  int64
 63   Subflow Fwd Bytes            170366 non-null  int64
 64   Subflow Bwd Packets          170366 non-null  int64
 65   Subflow Bwd Bytes            170366 non-null  int64
 66  Init_Win_bytes_forward        170366 non-null  int64
 67   Init_Win_bytes_backward      170366 non-null  int64
 68   act_data_pkt_fwd             170366 non-null  int64
 69   min_seg_size_forward         170366 non-null  int64
 70  Active Mean                   170366 non-null  float64
 71   Active Std                   170366 non-null  float64
 72   Active Max                   170366 non-null  int64
 73   Active Min                   170366 non-null  int64
 74  Idle Mean                     170366 non-null  float64
 75   Idle Std                     170366 non-null  float64
 76   Idle Max                     170366 non-null  int64
 77   Idle Min                     170366 non-null  int64
dtypes: float64(24), int64(54)
memory usage: 101.4 MB

In [9]:
X = X.fillna(X['Flow Bytes/s'].mean())
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170366 entries, 0 to 170365
Data columns (total 78 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0    Destination Port             170366 non-null  int64
 1    Flow Duration                170366 non-null  int64
 2    Total Fwd Packets            170366 non-null  int64
 3    Total Backward Packets       170366 non-null  int64
 4   Total Length of Fwd Packets   170366 non-null  int64
 5    Total Length of Bwd Packets  170366 non-null  int64
 6    Fwd Packet Length Max        170366 non-null  int64
 7    Fwd Packet Length Min        170366 non-null  int64
 8    Fwd Packet Length Mean       170366 non-null  float64
 9    Fwd Packet Length Std        170366 non-null  float64
 10  Bwd Packet Length Max         170366 non-null  int64
 11   Bwd Packet Length Min        170366 non-null  int64
 12   Bwd Packet Length Mean       170366 non-null  float64
 13   Bwd Packet Length Std        170366 non-null  float64
 14  Flow Bytes/s                  170366 non-null  float64
 15   Flow Packets/s               170366 non-null  float64
 16   Flow IAT Mean                170366 non-null  float64
 17   Flow IAT Std                 170366 non-null  float64
 18   Flow IAT Max                 170366 non-null  int64
 19   Flow IAT Min                 170366 non-null  int64
 20  Fwd IAT Total                 170366 non-null  int64
 21   Fwd IAT Mean                 170366 non-null  float64
 22   Fwd IAT Std                  170366 non-null  float64
 23   Fwd IAT Max                  170366 non-null  int64
 24   Fwd IAT Min                  170366 non-null  int64
 25  Bwd IAT Total                 170366 non-null  int64
 26   Bwd IAT Mean                 170366 non-null  float64
 27   Bwd IAT Std                  170366 non-null  float64
 28   Bwd IAT Max                  170366 non-null  int64
 29   Bwd IAT Min                  170366 non-null  int64
 30  Fwd PSH Flags                 170366 non-null  int64
 31   Bwd PSH Flags                170366 non-null  int64
 32   Fwd URG Flags                170366 non-null  int64
 33   Bwd URG Flags                170366 non-null  int64
 34   Fwd Header Length            170366 non-null  int64
 35   Bwd Header Length            170366 non-null  int64
 36  Fwd Packets/s                 170366 non-null  float64
 37   Bwd Packets/s                170366 non-null  float64
 38   Min Packet Length            170366 non-null  int64
 39   Max Packet Length            170366 non-null  int64
 40   Packet Length Mean           170366 non-null  float64
 41   Packet Length Std            170366 non-null  float64
 42   Packet Length Variance       170366 non-null  float64
 43  FIN Flag Count                170366 non-null  int64
 44   SYN Flag Count               170366 non-null  int64
 45   RST Flag Count               170366 non-null  int64
 46   PSH Flag Count               170366 non-null  int64
 47   ACK Flag Count               170366 non-null  int64
 48   URG Flag Count               170366 non-null  int64
 49   CWE Flag Count               170366 non-null  int64
 50   ECE Flag Count               170366 non-null  int64
 51   Down/Up Ratio                170366 non-null  int64
 52   Average Packet Size          170366 non-null  float64
 53   Avg Fwd Segment Size         170366 non-null  float64
 54   Avg Bwd Segment Size         170366 non-null  float64
 55   Fwd Header Length.1          170366 non-null  int64
 56  Fwd Avg Bytes/Bulk            170366 non-null  int64
 57   Fwd Avg Packets/Bulk         170366 non-null  int64
 58   Fwd Avg Bulk Rate            170366 non-null  int64
 59   Bwd Avg Bytes/Bulk           170366 non-null  int64
 60   Bwd Avg Packets/Bulk         170366 non-null  int64
 61  Bwd Avg Bulk Rate             170366 non-null  int64
 62  Subflow Fwd Packets           170366 non-null  int64
 63   Subflow Fwd Bytes            170366 non-null  int64
 64   Subflow Bwd Packets          170366 non-null  int64
 65   Subflow Bwd Bytes            170366 non-null  int64
 66  Init_Win_bytes_forward        170366 non-null  int64
 67   Init_Win_bytes_backward      170366 non-null  int64
 68   act_data_pkt_fwd             170366 non-null  int64
 69   min_seg_size_forward         170366 non-null  int64
 70  Active Mean                   170366 non-null  float64
 71   Active Std                   170366 non-null  float64
 72   Active Max                   170366 non-null  int64
 73   Active Min                   170366 non-null  int64
 74  Idle Mean                     170366 non-null  float64
 75   Idle Std                     170366 non-null  float64
 76   Idle Max                     170366 non-null  int64
 77   Idle Min                     170366 non-null  int64
dtypes: float64(24), int64(54)
memory usage: 101.4 MB

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split

In [11]:
print(np.isinf(X).sum())

 Destination Port              0
 Flow Duration                 0
 Total Fwd Packets             0
 Total Backward Packets        0
Total Length of Fwd Packets    0
                              ..
 Active Min                    0
Idle Mean                      0
 Idle Std                      0
 Idle Max                      0
 Idle Min                      0
Length: 78, dtype: int64

In [12]:
print(np.isnan(X).sum())

 Destination Port              0
 Flow Duration                 0
 Total Fwd Packets             0
 Total Backward Packets        0
Total Length of Fwd Packets    0
                              ..
 Active Min                    0
Idle Mean                      0
 Idle Std                      0
 Idle Max                      0
 Idle Min                      0
Length: 78, dtype: int64

In [13]:
X.replace([np.inf, -np.inf], np.nan, inplace=True)
X.fillna(X.median(), inplace =True)

In [14]:
bad_rows = X[np.isnan(X).any(axis = 1) | np.isinf(X).any(axis=1)]

In [15]:
bad_rows

Empty DataFrame
Columns: [ Destination Port,  Flow Duration,  Total Fwd Packets,  Total Backward Packets, Total Length of Fwd Packets,  Total Length of Bwd Packets,  Fwd Packet Length Max,  Fwd Packet Length Min,  Fwd Packet Length Mean,  Fwd Packet Length Std, Bwd Packet Length Max,  Bwd Packet Length Min,  Bwd Packet Length Mean,  Bwd Packet Length Std, Flow Bytes/s,  Flow Packets/s,  Flow IAT Mean,  Flow IAT Std,  Flow IAT Max,  Flow IAT Min, Fwd IAT Total,  Fwd IAT Mean,  Fwd IAT Std,  Fwd IAT Max,  Fwd IAT Min, Bwd IAT Total,  Bwd IAT Mean,  Bwd IAT Std,  Bwd IAT Max,  Bwd IAT Min, Fwd PSH Flags,  Bwd PSH Flags,  Fwd URG Flags,  Bwd URG Flags,  Fwd Header Length,  Bwd Header Length, Fwd Packets/s,  Bwd Packets/s,  Min Packet Length,  Max Packet Length,  Packet Length Mean,  Packet Length Std,  Packet Length Variance, FIN Flag Count,  SYN Flag Count,  RST Flag Count,  PSH Flag Count,  ACK Flag Count,  URG Flag Count,  CWE Flag Count,  ECE Flag Count,  Down/Up Ratio,  Average Packet Size,  Avg Fwd Segment Size,  Avg Bwd Segment Size,  Fwd Header Length.1, Fwd Avg Bytes/Bulk,  Fwd Avg Packets/Bulk,  Fwd Avg Bulk Rate,  Bwd Avg Bytes/Bulk,  Bwd Avg Packets/Bulk, Bwd Avg Bulk Rate, Subflow Fwd Packets,  Subflow Fwd Bytes,  Subflow Bwd Packets,  Subflow Bwd Bytes, Init_Win_bytes_forward,  Init_Win_bytes_backward,  act_data_pkt_fwd,  min_seg_size_forward, Active Mean,  Active Std,  Active Max,  Active Min, Idle Mean,  Idle Std,  Idle Max,  Idle Min]
Index: []

[0 rows x 78 columns]

In [16]:
y

0         BENIGN
1         BENIGN
2         BENIGN
3         BENIGN
4         BENIGN
           ...
170361    BENIGN
170362    BENIGN
170363    BENIGN
170364    BENIGN
170365    BENIGN
Name:  Label, Length: 170366, dtype: object

In [17]:
x_train, x_test, y_train, y_test =train_test_split(X, y, test_size=0.2, random_state = 4000)

In [ ]:
model = LogisticRegression(max_iter = 5000)

model.fit(x_train ,y_train)

y_pred = model.predict(x_test)