In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot  as plt

In [2]:
df = pd.read_csv("D:\onedrive\Desktop\CIC DDOS 2017 DATA_SET\Monday-WorkingHours.pcap_ISCX.csv")

In [3]:
df.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,49188,4,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,49188,1,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,49188,1,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,49188,1,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,49486,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [4]:
#df['Destination Port']
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 529918 entries, 0 to 529917
Data columns (total 79 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0    Destination Port             529918 non-null  int64
 1    Flow Duration                529918 non-null  int64
 2    Total Fwd Packets            529918 non-null  int64
 3    Total Backward Packets       529918 non-null  int64
 4   Total Length of Fwd Packets   529918 non-null  int64
 5    Total Length of Bwd Packets  529918 non-null  int64
 6    Fwd Packet Length Max        529918 non-null  int64
 7    Fwd Packet Length Min        529918 non-null  int64
 8    Fwd Packet Length Mean       529918 non-null  float64
 9    Fwd Packet Length Std        529918 non-null  float64
 10  Bwd Packet Length Max         529918 non-null  int64
 11   Bwd Packet Length Min        529918 non-null  int64
 12   Bwd Packet Length Mean       529918 non-null  float64
 13   Bwd Packet Length Std        529918 non-null  float64
 14  Flow Bytes/s                  529854 non-null  float64
 15   Flow Packets/s               529918 non-null  float64
 16   Flow IAT Mean                529918 non-null  float64
 17   Flow IAT Std                 529918 non-null  float64
 18   Flow IAT Max                 529918 non-null  int64
 19   Flow IAT Min                 529918 non-null  int64
 20  Fwd IAT Total                 529918 non-null  int64
 21   Fwd IAT Mean                 529918 non-null  float64
 22   Fwd IAT Std                  529918 non-null  float64
 23   Fwd IAT Max                  529918 non-null  int64
 24   Fwd IAT Min                  529918 non-null  int64
 25  Bwd IAT Total                 529918 non-null  int64
 26   Bwd IAT Mean                 529918 non-null  float64
 27   Bwd IAT Std                  529918 non-null  float64
 28   Bwd IAT Max                  529918 non-null  int64
 29   Bwd IAT Min                  529918 non-null  int64
 30  Fwd PSH Flags                 529918 non-null  int64
 31   Bwd PSH Flags                529918 non-null  int64
 32   Fwd URG Flags                529918 non-null  int64
 33   Bwd URG Flags                529918 non-null  int64
 34   Fwd Header Length            529918 non-null  int64
 35   Bwd Header Length            529918 non-null  int64
 36  Fwd Packets/s                 529918 non-null  float64
 37   Bwd Packets/s                529918 non-null  float64
 38   Min Packet Length            529918 non-null  int64
 39   Max Packet Length            529918 non-null  int64
 40   Packet Length Mean           529918 non-null  float64
 41   Packet Length Std            529918 non-null  float64
 42   Packet Length Variance       529918 non-null  float64
 43  FIN Flag Count                529918 non-null  int64
 44   SYN Flag Count               529918 non-null  int64
 45   RST Flag Count               529918 non-null  int64
 46   PSH Flag Count               529918 non-null  int64
 47   ACK Flag Count               529918 non-null  int64
 48   URG Flag Count               529918 non-null  int64
 49   CWE Flag Count               529918 non-null  int64
 50   ECE Flag Count               529918 non-null  int64
 51   Down/Up Ratio                529918 non-null  int64
 52   Average Packet Size          529918 non-null  float64
 53   Avg Fwd Segment Size         529918 non-null  float64
 54   Avg Bwd Segment Size         529918 non-null  float64
 55   Fwd Header Length.1          529918 non-null  int64
 56  Fwd Avg Bytes/Bulk            529918 non-null  int64
 57   Fwd Avg Packets/Bulk         529918 non-null  int64
 58   Fwd Avg Bulk Rate            529918 non-null  int64
 59   Bwd Avg Bytes/Bulk           529918 non-null  int64
 60   Bwd Avg Packets/Bulk         529918 non-null  int64
 61  Bwd Avg Bulk Rate             529918 non-null  int64
 62  Subflow Fwd Packets           529918 non-null  int64
 63   Subflow Fwd Bytes            529918 non-null  int64
 64   Subflow Bwd Packets          529918 non-null  int64
 65   Subflow Bwd Bytes            529918 non-null  int64
 66  Init_Win_bytes_forward        529918 non-null  int64
 67   Init_Win_bytes_backward      529918 non-null  int64
 68   act_data_pkt_fwd             529918 non-null  int64
 69   min_seg_size_forward         529918 non-null  int64
 70  Active Mean                   529918 non-null  float64
 71   Active Std                   529918 non-null  float64
 72   Active Max                   529918 non-null  int64
 73   Active Min                   529918 non-null  int64
 74  Idle Mean                     529918 non-null  float64
 75   Idle Std                     529918 non-null  float64
 76   Idle Max                     529918 non-null  int64
 77   Idle Min                     529918 non-null  int64
 78   Label                        529918 non-null  object
dtypes: float64(24), int64(54), object(1)
memory usage: 319.4+ MB

In [5]:
X = df
X = X.drop(' Label',axis= 1)

In [6]:
y = df.iloc[:,78]

In [7]:
y

0         BENIGN
1         BENIGN
2         BENIGN
3         BENIGN
4         BENIGN
           ...
529913    BENIGN
529914    BENIGN
529915    BENIGN
529916    BENIGN
529917    BENIGN
Name:  Label, Length: 529918, dtype: object

In [8]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 529918 entries, 0 to 529917
Data columns (total 78 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0    Destination Port             529918 non-null  int64
 1    Flow Duration                529918 non-null  int64
 2    Total Fwd Packets            529918 non-null  int64
 3    Total Backward Packets       529918 non-null  int64
 4   Total Length of Fwd Packets   529918 non-null  int64
 5    Total Length of Bwd Packets  529918 non-null  int64
 6    Fwd Packet Length Max        529918 non-null  int64
 7    Fwd Packet Length Min        529918 non-null  int64
 8    Fwd Packet Length Mean       529918 non-null  float64
 9    Fwd Packet Length Std        529918 non-null  float64
 10  Bwd Packet Length Max         529918 non-null  int64
 11   Bwd Packet Length Min        529918 non-null  int64
 12   Bwd Packet Length Mean       529918 non-null  float64
 13   Bwd Packet Length Std        529918 non-null  float64
 14  Flow Bytes/s                  529854 non-null  float64
 15   Flow Packets/s               529918 non-null  float64
 16   Flow IAT Mean                529918 non-null  float64
 17   Flow IAT Std                 529918 non-null  float64
 18   Flow IAT Max                 529918 non-null  int64
 19   Flow IAT Min                 529918 non-null  int64
 20  Fwd IAT Total                 529918 non-null  int64
 21   Fwd IAT Mean                 529918 non-null  float64
 22   Fwd IAT Std                  529918 non-null  float64
 23   Fwd IAT Max                  529918 non-null  int64
 24   Fwd IAT Min                  529918 non-null  int64
 25  Bwd IAT Total                 529918 non-null  int64
 26   Bwd IAT Mean                 529918 non-null  float64
 27   Bwd IAT Std                  529918 non-null  float64
 28   Bwd IAT Max                  529918 non-null  int64
 29   Bwd IAT Min                  529918 non-null  int64
 30  Fwd PSH Flags                 529918 non-null  int64
 31   Bwd PSH Flags                529918 non-null  int64
 32   Fwd URG Flags                529918 non-null  int64
 33   Bwd URG Flags                529918 non-null  int64
 34   Fwd Header Length            529918 non-null  int64
 35   Bwd Header Length            529918 non-null  int64
 36  Fwd Packets/s                 529918 non-null  float64
 37   Bwd Packets/s                529918 non-null  float64
 38   Min Packet Length            529918 non-null  int64
 39   Max Packet Length            529918 non-null  int64
 40   Packet Length Mean           529918 non-null  float64
 41   Packet Length Std            529918 non-null  float64
 42   Packet Length Variance       529918 non-null  float64
 43  FIN Flag Count                529918 non-null  int64
 44   SYN Flag Count               529918 non-null  int64
 45   RST Flag Count               529918 non-null  int64
 46   PSH Flag Count               529918 non-null  int64
 47   ACK Flag Count               529918 non-null  int64
 48   URG Flag Count               529918 non-null  int64
 49   CWE Flag Count               529918 non-null  int64
 50   ECE Flag Count               529918 non-null  int64
 51   Down/Up Ratio                529918 non-null  int64
 52   Average Packet Size          529918 non-null  float64
 53   Avg Fwd Segment Size         529918 non-null  float64
 54   Avg Bwd Segment Size         529918 non-null  float64
 55   Fwd Header Length.1          529918 non-null  int64
 56  Fwd Avg Bytes/Bulk            529918 non-null  int64
 57   Fwd Avg Packets/Bulk         529918 non-null  int64
 58   Fwd Avg Bulk Rate            529918 non-null  int64
 59   Bwd Avg Bytes/Bulk           529918 non-null  int64
 60   Bwd Avg Packets/Bulk         529918 non-null  int64
 61  Bwd Avg Bulk Rate             529918 non-null  int64
 62  Subflow Fwd Packets           529918 non-null  int64
 63   Subflow Fwd Bytes            529918 non-null  int64
 64   Subflow Bwd Packets          529918 non-null  int64
 65   Subflow Bwd Bytes            529918 non-null  int64
 66  Init_Win_bytes_forward        529918 non-null  int64
 67   Init_Win_bytes_backward      529918 non-null  int64
 68   act_data_pkt_fwd             529918 non-null  int64
 69   min_seg_size_forward         529918 non-null  int64
 70  Active Mean                   529918 non-null  float64
 71   Active Std                   529918 non-null  float64
 72   Active Max                   529918 non-null  int64
 73   Active Min                   529918 non-null  int64
 74  Idle Mean                     529918 non-null  float64
 75   Idle Std                     529918 non-null  float64
 76   Idle Max                     529918 non-null  int64
 77   Idle Min                     529918 non-null  int64
dtypes: float64(24), int64(54)
memory usage: 315.4 MB

In [9]:
X = X.fillna(X['Flow Bytes/s'].mean())
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 529918 entries, 0 to 529917
Data columns (total 78 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0    Destination Port             529918 non-null  int64
 1    Flow Duration                529918 non-null  int64
 2    Total Fwd Packets            529918 non-null  int64
 3    Total Backward Packets       529918 non-null  int64
 4   Total Length of Fwd Packets   529918 non-null  int64
 5    Total Length of Bwd Packets  529918 non-null  int64
 6    Fwd Packet Length Max        529918 non-null  int64
 7    Fwd Packet Length Min        529918 non-null  int64
 8    Fwd Packet Length Mean       529918 non-null  float64
 9    Fwd Packet Length Std        529918 non-null  float64
 10  Bwd Packet Length Max         529918 non-null  int64
 11   Bwd Packet Length Min        529918 non-null  int64
 12   Bwd Packet Length Mean       529918 non-null  float64
 13   Bwd Packet Length Std        529918 non-null  float64
 14  Flow Bytes/s                  529918 non-null  float64
 15   Flow Packets/s               529918 non-null  float64
 16   Flow IAT Mean                529918 non-null  float64
 17   Flow IAT Std                 529918 non-null  float64
 18   Flow IAT Max                 529918 non-null  int64
 19   Flow IAT Min                 529918 non-null  int64
 20  Fwd IAT Total                 529918 non-null  int64
 21   Fwd IAT Mean                 529918 non-null  float64
 22   Fwd IAT Std                  529918 non-null  float64
 23   Fwd IAT Max                  529918 non-null  int64
 24   Fwd IAT Min                  529918 non-null  int64
 25  Bwd IAT Total                 529918 non-null  int64
 26   Bwd IAT Mean                 529918 non-null  float64
 27   Bwd IAT Std                  529918 non-null  float64
 28   Bwd IAT Max                  529918 non-null  int64
 29   Bwd IAT Min                  529918 non-null  int64
 30  Fwd PSH Flags                 529918 non-null  int64
 31   Bwd PSH Flags                529918 non-null  int64
 32   Fwd URG Flags                529918 non-null  int64
 33   Bwd URG Flags                529918 non-null  int64
 34   Fwd Header Length            529918 non-null  int64
 35   Bwd Header Length            529918 non-null  int64
 36  Fwd Packets/s                 529918 non-null  float64
 37   Bwd Packets/s                529918 non-null  float64
 38   Min Packet Length            529918 non-null  int64
 39   Max Packet Length            529918 non-null  int64
 40   Packet Length Mean           529918 non-null  float64
 41   Packet Length Std            529918 non-null  float64
 42   Packet Length Variance       529918 non-null  float64
 43  FIN Flag Count                529918 non-null  int64
 44   SYN Flag Count               529918 non-null  int64
 45   RST Flag Count               529918 non-null  int64
 46   PSH Flag Count               529918 non-null  int64
 47   ACK Flag Count               529918 non-null  int64
 48   URG Flag Count               529918 non-null  int64
 49   CWE Flag Count               529918 non-null  int64
 50   ECE Flag Count               529918 non-null  int64
 51   Down/Up Ratio                529918 non-null  int64
 52   Average Packet Size          529918 non-null  float64
 53   Avg Fwd Segment Size         529918 non-null  float64
 54   Avg Bwd Segment Size         529918 non-null  float64
 55   Fwd Header Length.1          529918 non-null  int64
 56  Fwd Avg Bytes/Bulk            529918 non-null  int64
 57   Fwd Avg Packets/Bulk         529918 non-null  int64
 58   Fwd Avg Bulk Rate            529918 non-null  int64
 59   Bwd Avg Bytes/Bulk           529918 non-null  int64
 60   Bwd Avg Packets/Bulk         529918 non-null  int64
 61  Bwd Avg Bulk Rate             529918 non-null  int64
 62  Subflow Fwd Packets           529918 non-null  int64
 63   Subflow Fwd Bytes            529918 non-null  int64
 64   Subflow Bwd Packets          529918 non-null  int64
 65   Subflow Bwd Bytes            529918 non-null  int64
 66  Init_Win_bytes_forward        529918 non-null  int64
 67   Init_Win_bytes_backward      529918 non-null  int64
 68   act_data_pkt_fwd             529918 non-null  int64
 69   min_seg_size_forward         529918 non-null  int64
 70  Active Mean                   529918 non-null  float64
 71   Active Std                   529918 non-null  float64
 72   Active Max                   529918 non-null  int64
 73   Active Min                   529918 non-null  int64
 74  Idle Mean                     529918 non-null  float64
 75   Idle Std                     529918 non-null  float64
 76   Idle Max                     529918 non-null  int64
 77   Idle Min                     529918 non-null  int64
dtypes: float64(24), int64(54)
memory usage: 315.4 MB

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split

In [14]:
print(np.isinf(X).sum())

 Destination Port              0
 Flow Duration                 0
 Total Fwd Packets             0
 Total Backward Packets        0
Total Length of Fwd Packets    0
                              ..
 Active Min                    0
Idle Mean                      0
 Idle Std                      0
 Idle Max                      0
 Idle Min                      0
Length: 78, dtype: int64

In [19]:
print(np.isnan(X).sum())

 Destination Port              0
 Flow Duration                 0
 Total Fwd Packets             0
 Total Backward Packets        0
Total Length of Fwd Packets    0
                              ..
 Active Min                    0
Idle Mean                      0
 Idle Std                      0
 Idle Max                      0
 Idle Min                      0
Length: 78, dtype: int64

In [22]:
X.replace([np.inf, -np.inf], np.nan, inplace=True)
X.fillna(X.median(), inplace =True)

In [27]:
bad_rows = X[np.isnan(X).any(axis = 1) | np.isinf(X).any(axis=1)]

In [28]:
bad_rows

Empty DataFrame
Columns: [ Destination Port,  Flow Duration,  Total Fwd Packets,  Total Backward Packets, Total Length of Fwd Packets,  Total Length of Bwd Packets,  Fwd Packet Length Max,  Fwd Packet Length Min,  Fwd Packet Length Mean,  Fwd Packet Length Std, Bwd Packet Length Max,  Bwd Packet Length Min,  Bwd Packet Length Mean,  Bwd Packet Length Std, Flow Bytes/s,  Flow Packets/s,  Flow IAT Mean,  Flow IAT Std,  Flow IAT Max,  Flow IAT Min, Fwd IAT Total,  Fwd IAT Mean,  Fwd IAT Std,  Fwd IAT Max,  Fwd IAT Min, Bwd IAT Total,  Bwd IAT Mean,  Bwd IAT Std,  Bwd IAT Max,  Bwd IAT Min, Fwd PSH Flags,  Bwd PSH Flags,  Fwd URG Flags,  Bwd URG Flags,  Fwd Header Length,  Bwd Header Length, Fwd Packets/s,  Bwd Packets/s,  Min Packet Length,  Max Packet Length,  Packet Length Mean,  Packet Length Std,  Packet Length Variance, FIN Flag Count,  SYN Flag Count,  RST Flag Count,  PSH Flag Count,  ACK Flag Count,  URG Flag Count,  CWE Flag Count,  ECE Flag Count,  Down/Up Ratio,  Average Packet Size,  Avg Fwd Segment Size,  Avg Bwd Segment Size,  Fwd Header Length.1, Fwd Avg Bytes/Bulk,  Fwd Avg Packets/Bulk,  Fwd Avg Bulk Rate,  Bwd Avg Bytes/Bulk,  Bwd Avg Packets/Bulk, Bwd Avg Bulk Rate, Subflow Fwd Packets,  Subflow Fwd Bytes,  Subflow Bwd Packets,  Subflow Bwd Bytes, Init_Win_bytes_forward,  Init_Win_bytes_backward,  act_data_pkt_fwd,  min_seg_size_forward, Active Mean,  Active Std,  Active Max,  Active Min, Idle Mean,  Idle Std,  Idle Max,  Idle Min]
Index: []

[0 rows x 78 columns]

In [31]:
y

0         BENIGN
1         BENIGN
2         BENIGN
3         BENIGN
4         BENIGN
           ...
529913    BENIGN
529914    BENIGN
529915    BENIGN
529916    BENIGN
529917    BENIGN
Name:  Label, Length: 529918, dtype: object

In [29]:
x_train, y_train, x_test, y_test =train_test_split(X, y, test_size=0.2, random_state = 42)

In [30]:
model = LogisticRegression(max_iter = 100)

model.fit(x_train ,y_train)

y_pred = model.predict(x_test)

ValueError: y should be a 1d array, got an array of shape (105984, 78) instead.